-- ═══════════════════════════════════════════════════════════
-- Migration: Add AI 3D Generation fields to dishes table
-- Run this in Supabase Dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════

-- Track whether a 3D model was generated by AI
ALTER TABLE dishes ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Track Meshy/Stability task ID (for async flows if needed later)
ALTER TABLE dishes ADD COLUMN IF NOT EXISTS ai_generation_task_id TEXT;

-- Also ensure model_3d_status exists (may already exist)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'dishes' AND column_name = 'model_3d_status'
  ) THEN
    ALTER TABLE dishes ADD COLUMN model_3d_status TEXT DEFAULT 'NONE';
  END IF;
END $$;

-- Ensure model_3d_size_kb exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'dishes' AND column_name = 'model_3d_size_kb'
  ) THEN
    ALTER TABLE dishes ADD COLUMN model_3d_size_kb INTEGER;
  END IF;
END $$;

-- Ensure model_3d_uploaded_at exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'dishes' AND column_name = 'model_3d_uploaded_at'
  ) THEN
    ALTER TABLE dishes ADD COLUMN model_3d_uploaded_at TIMESTAMPTZ;
  END IF;
END $$;

-- Index for faster AI status queries
CREATE INDEX IF NOT EXISTS idx_dishes_ai_status 
  ON dishes (model_3d_status) 
  WHERE model_3d_status = 'PROCESSING';
